[tool.poetry]
name = "pythonproject3"
version = "0.1.0"
description = ""
authors = ["Ulyana Kuznetsova <rey.tsvetkov777@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
